# Generated by Django 3.2.12 on 2024-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_treenode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='diamond',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='text',
        ),
        migrations.AddField(
            model_name='treenode',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treenode',
            name='roll_no',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
