# Generated by Django 3.2.12 on 2024-03-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20240309_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeNode',
        ),
    ]
