name: 🐛 Bug Report
description: Report a reproducible bug or regression in IITJ Faamily Tree.
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: os
    attributes:
      label: "Operating system"
      multiple: false
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Android"
        - "iOS"
    validations:
      required: true
      
  
  - type: textarea
    id: current
    attributes:
      label: Current behaviour
      description: Include screenshots or video recordings for UI problems if needed.
      placeholder: |
        1. This
        2. Then that
        3. Then this
        4. Etc.

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to do?
